#Deploy the databricks note book to main branch
name: deploy-to-main
on:
  #Trigger workflow on push or pull request but only for main branch
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-main-to-dev:
    uses: ./.github/workflows/shared-workflow.databricks.deploy.yml@main
    with:
      DATABRICKS_HOST: https://adb-4158740886800280.0.azuredatabricks.net/
      DATABRICKS_MANAGED_DIRECTORY: "/BrandPulse"
      ENVIRONMENT: dev
    secrets:
      DATABRICKS_TOKEN: ${{secrects.DATABRICKS_TOKEN}}